#!/bin/bash

################## CONFIG ######################
MY_VERSION=2

CLEAR_TOOLCHAIN="NO"
BUILD_TOOLCHAIN="NO"

BUILD_FIRMWARE="YES"
## Only used if BUILD_FIRMWARE="YES"##
## Comment out the lines containing configs you don't want to build.
BUILD_FIRMWARE_CF=(\
		   n56u_qos_k3.0.config \
		   n56u_qos.config \
		   n65u_qos.config \
		   n14u_qos_full.config \
		   )
################################################

# $1 - config file
change_version()
{
  sed -i "s/\(CONFIG_FIRMWARE_BUILDS_VER\=\"[0-9]*-moonman-\).*/\1$MY_VERSION\"/" $1
}


# $1 - config file name
evaluate_path()
{
  case "$1" in
	n56u_qos_k3.0.config)
		_path="N56U/k3.0"
		;;
	n56u_qos.config)
		_path="N56U/k3.4"
		;;
	n65u_qos.config)
		_path="N65U"
		;;
	n14u_qos_full.config)
		_path="N14U"
		;;
	*)
		echo "Unknown config. Aborting..." && exit 1
		;;
  esac
  echo "$_path"

}

if [ $BUILD_TOOLCHAIN = "YES" ]
then
  cd ../toolchain-rt3883

  if [ $CLEAR_TOOLCHAIN = "YES" ]
  then
     ./clean_toolchain_3.0.x
     ./clean_toolchain_3.4.x
  fi

  ./clean_sources
  ./build_toolchain

  ./clean_sources
  ./build_toolchain_3.4.x
   ./clean_sources
fi

if [ $BUILD_FIRMWARE = "YES" ]
then

  cd ../trunk
  ./clear_tree

  for fw in ${BUILD_FIRMWARE_CF[@]}; do
    cp ./configs/$fw ./.config
    #Replace version number to new
    change_version ./.config

    ./build_firmware || exit 1
    cp ./images/RT-N* ../images/$(evaluate_path $fw)

    #if build successful, change version in the reference config too
    change_version ./configs/$fw

    ./clear_tree
  done

  cp ./configs/n56u_qos.config ./.config
fi
