#!/bin/bash

################## CONFIG ######################
CLEAR_TOOLCHAIN="NO"
BUILD_TOOLCHAIN="NO"

BUILD_FIRMWARE_GEN="YES"
## Only used if BUILD_FIRMWARE_GEN="YES"##
BUILD_FIRMWARE_N56U="YES"
BUILD_FIRMWARE_N65U="YES"
BUILD_FIRMWARE_N14U="YES"
################################################

if [ $BUILD_TOOLCHAIN = "YES" ]
then
  cd ../toolchain-rt3883

  if [ $CLEAR_TOOLCHAIN = "YES" ]
  then
     ./clean_toolchain_3.0.x
     ./clean_toolchain_3.4.x
  fi

  ./clean_sources
  ./build_toolchain

  ./clean_sources
  ./build_toolchain_3.4.x
   ./clean_sources
fi

if [ $BUILD_FIRMWARE_GEN = "YES" ]
then

  cd ../trunk
  ./clear_tree

  if [ $BUILD_FIRMWARE_N56U = "YES" ]
  then
    cp ./configs/n56u_qos.config ./.config
    ./build_firmware
    cp ./images/RT-N* ../images/N56U/
    ./clear_tree
  fi

  if [ $BUILD_FIRMWARE_N65U = "YES" ]
  then
    cp ./configs/n65u_qos.config ./.config
    ./build_firmware
    cp ./images/RT-N* ../images/N65U/
    ./clear_tree
  fi

  if [ $BUILD_FIRMWARE_N14U = "YES" ]
  then
    cp ./configs/n14u_qos_full.config ./.config
    ./build_firmware
    cp ./images/RT-N* ../images/N14U/
    ./clear_tree
  fi

  cp ./configs/n56u_qos.config ./.config
fi
